name: Mirror
options:
  bundleIdPrefix: net.aagaard
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  developmentLanguage: en

targets:
  Mirror:
    type: application
    platform: iOS
    sources:
      - path: Mirror
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: "iPhone Developer"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: 6UXZ93SX6E
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Mirror"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_NSCameraUsageDescription: "To use the screen as a mirror."
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        MARKETING_VERSION: "1.0"
        PRODUCT_BUNDLE_IDENTIFIER: net.aagaard.mirror
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
